spring:
  datasource:
    url: jdbc:h2:file:./h2/db
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2_console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: h2

server:
  error:
    include-message: always

verifier:
  username: affinidi_oidc_verifier
  password: "@ffO1dcVcAuthN"

verifierApi:
  url: https://affinity-verifier.dev.affinity-project.org/api/v1
  apiKey: c01ff09031bdce0571ede599fd0ced5ab7f539b4039cc4ca105c9ca3f68613b0

cloudWalletApi:
  url: https://cloud-wallet-api.dev.affinity-project.org/api/v1
  apiKey: c01ff09031bdce0571ede599fd0ced5ab7f539b4039cc4ca105c9ca3f68613b0

logging:
  level:
    root: info

feign:
  client:
    config:
      default:
        loggerLevel: full

self:
  baseUrl: http://localhost:8080
