spring:
  datasource:
    url: jdbc:h2:file:./h2/db
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2_console

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: h2

server:
  error:
    include-message: always

verifier:
  username: <verifier_username>
  password: <verifier_password>

verifierApi:
  url: <verifier_api_url>
  apiKey: <verifier_api_key>

cloudWalletApi:
  url: <wallet_api_url>
  apiKey: <wallet_api_key>

logging:
  level:
    root: info

feign:
  client:
    config:
      default:
        loggerLevel: full
